<?php

return [
    [
        'type' => 'array',
        'name' => 'companytype',
        'title' => '企业类型',
        'value' => [
            'myself' => '自营',
            'other' => '其他',
        ],
        'content' => [
            'value1' => 'title1',
            'value2' => 'title2',
        ],
        'tip' => '',
        'rule' => 'required',
        'extend' => '',
    ],
    [
        'type' => 'array',
        'name' => 'configgroup',
        'title' => '配置分组',
        'value' => [
            'basic' => '基础配置',
        ],
        'content' => [
            'value1' => 'title1',
            'value2' => 'title2',
        ],
        'tip' => '配置分组',
        'rule' => 'required',
        'extend' => '',
    ],
    [
        'type' => 'string',
        'name' => 'coordinate',
        'title' => '平台坐标',
        'value' => '22.99913,113.71120',
        'content' => '',
        'tip' => '格式为：经度,纬度',
        'rule' => '',
        'extend' => '',
    ],
    [
        'name' => 'termvalidity',
        'title' => '有限期控制',
        'type' => 'radio',
        'content' => [
            'off' => '关闭',
            'vip' => '同步官方VIP(如需要请自行购买)',
        ],
        'value' => 'off',
        'rule' => 'required',
        'msg' => '',
        'tip' => '温馨提示：VIP插件为官方插件，如需要请自行购买',
        'ok' => '',
        'extend' => '',
    ],
    [
        'type' => 'string',
        'name' => 'ssldir',
        'title' => 'SSL证书安装路径',
        'value' => '',
        'content' => '',
        'tip' => '请保证文件夹可读写',
        'rule' => '',
        'extend' => '',
    ],
    [
        'type' => 'string',
        'name' => 'fixedpage',
        'title' => '企业首页页面',
        'value' => '/web.html',
        'content' => '',
        'tip' => '企业首页页面控制器',
        'rule' => '',
        'extend' => '',
    ],
    [
        'name' => 'rewrite',
        'title' => '伪静态配置',
        'type' => 'array',
        'content' => [],
        'value' => [
            'web/index' => '/web$',
            'web/content' => '/web/content$',
            'web/product' => '/web/product$',
            'web/single' => '/web/single$',
            'web/product_detail' => '/web/product/detail$',
            'web/content_detail' => '/web/content/detail$',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'type' => 'image',
        'name' => 'indexbackground',
        'title' => '首页背景图片',
        'value' => '',
        'content' => '',
        'tip' => '首页背景图片',
        'rule' => '',
        'extend' => '',
    ],
    [
        'name' => 'domain',
        'title' => '绑定二级域名前缀',
        'type' => 'string',
        'content' => [],
        'value' => 'admin',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
