<?php

return [
    [
        'name' => 'theme',
        'title' => '选择主题',
        'type' => 'select',
        'content' => [
            'ambiance' => 'Ambiance',
            'chaos' => 'Chaos',
            'chrome' => 'Chrome',
            'clouds' => 'Clouds',
            'clouds_midnight' => 'Clouds Midnight',
            'cobalt' => 'Cobalt',
            'crimson_editor' => 'Crimson Editor',
            'dawn' => 'Dawn',
            'dracula' => 'Dracula',
            'dreamweaver' => 'Dreamweaver',
            'eclipse' => 'Eclipse',
            'github' => 'Github',
            'gob' => 'Gob',
            'gruvbox' => 'Gruvbox',
            'idle_fingers' => 'Idle Fingers',
            'iplastic' => 'Iplastic',
            'katzenmilch' => 'Katzenmilch',
            'kr_theme' => 'Kr Theme',
            'kuroir' => 'kuroir',
            'merbivore' => 'Merbivore',
            'merbivore_soft' => 'Merbivore Soft',
            'mono_industrial' => 'Mono Industrial',
            'monokai' => 'Monokai',
            'pastel_on_dark' => 'Pastel On Dark',
            'solarized_dark' => 'Solarized Dark',
            'solarized_light' => 'Solarized Light',
            'sqlserver' => 'Sqlserver',
            'terminal' => 'Terminal',
            'textmate' => 'Textmate',
            'tomorrow' => 'Tomorrow',
            'tomorrow_night' => 'Tomorrow Night',
            'tomorrow_night_blue' => 'Tomorrow Night Blue',
            'tomorrow_night_bright' => 'Tomorrow Night Bright',
            'tomorrow_night_eighties' => 'Tomorrow Night Eighties',
            'twilight' => 'Twilight',
            'vibrant_ink' => 'Vibrant Ink',
            'xcode' => 'Xcode',
        ],
        'value' => 'xcode',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => 'data-live-search="true"',
    ],
    [
        'name' => 'font_size',
        'title' => '字体大小',
        'type' => 'string',
        'content' => '',
        'value' => '13',
        'rule' => 'required',
        'msg' => '',
        'tip' => 'px',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'setreadonly',
        'title' => '是否只读',
        'type' => 'radio',
        'content' => [
            '否',
            '是',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'auto_wrap',
        'title' => '自动换行',
        'type' => 'radio',
        'content' => [
            'free' => '是',
            'off' => '否',
        ],
        'value' => 'free',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name'    => '__tips__',
        'title'   => '温馨提示',
        'type'    => 'string',
        'content' => [],
        'value'   => '为了你的站点安全，该插件仅在调试模式下可用',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
];
