<?php

return [
    [
        'name' => 'logo',
        'title' => 'Logo',
        'type' => 'image',
        'content' => [],
        'value' => '/assets/addons/mylogin/img/logo.png',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'copyright',
        'title' => '版权信息',
        'type' => 'string',
        'content' => [],
        'value' => 'Copyright © 2022-2023 后台登录页插件 版权所有',
        'visible' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => 'placeholder="登录页下方显示的版权信息，为空则不显示"',
    ],
    [
        'name' => 'theme',
        'title' => '选择样式',
        'type' => 'select',
        'content' => [
            'one' => '白色背景(居中)&nbsp;&nbsp;',
            'two' => '蓝色背景(居中)&nbsp;&nbsp;',
            'three' => '白色背景(居右)&nbsp;&nbsp;',
            'four' => '风景背景(居中)&nbsp;&nbsp;',
            'five' => '紫蓝背景(居中)&nbsp;&nbsp;',
        ],
        'value' => 'five',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'one',
        'title' => '',
        'type' => 'preview',
        'content' => [],
        'value' => '/assets/addons/mylogin/img/one/preview.png',
        'visible'  => 'theme=one',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'two',
        'title' => '',
        'type' => 'preview',
        'content' => [],
        'value' => '/assets/addons/mylogin/img/two/preview.png',
        'visible'  => 'theme=two',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'three',
        'title' => '',
        'type' => 'preview',
        'content' => [],
        'value' => '/assets/addons/mylogin/img/three/preview.png',
        'visible'  => 'theme=three',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'four',
        'title' => '',
        'type' => 'preview',
        'content' => [],
        'value' => '/assets/addons/mylogin/img/four/preview.png',
        'visible' => 'theme=four',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => '__tips__',
        'title' => '温馨提示',
        'type' => 'string',
        'content' => [],
        'value' => '如果您修改过原登录页面样式或login.html代码结构导致启用本插件后布局错乱等问题，请手动备份好原来的login.html代码并还原为官方默认样式即可。',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];