<?php

return [
    [
        'name' => 'corp_id',
        'title' => '企业ID',
        'type' => 'string',
        'group' => '企微设置',
        'visible' => '',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '企微管理后台-我的企业中获取',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'H5_agent_id',
        'title' => 'H5应用AgentId',
        'group' => '企微设置',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '企微管理后台-应用管理-AgentId获取(H5使用)',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'App_address_secret',
        'title' => '小程序应用Secret',
        'group' => '企微设置',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '企微管理后台-应用管理-Secret获取(小程序使用)',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'H5_address_secret',
        'title' => 'H5应用Secret',
        'group' => '企微设置',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '企微管理后台-应用管理-Secret获取(H5使用)',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'address_secret',
        'title' => '通讯录Secret',
        'type' => 'string',
        'group' => '通讯录',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '企微管理后台-管理工具-通讯录同步中获取',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'address_Token',
        'title' => '通讯录回调Token',
        'group' => '通讯录',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '企微管理后台-管理工具-通讯录api-设置接收事件服务器',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'address_EncodingAESKey',
        'title' => '通讯录回调EncodingAESKey',
        'group' => '通讯录',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '企微管理后台-管理工具-通讯录api-设置接收事件服务器',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'Ext_address_secret',
        'title' => '客户Secret',
        'group' => '客户联系',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '企微管理后台-客户与上下游-API-Secret获取',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'Ext_Token',
        'title' => '客户回调Token',
        'group' => '客户联系',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '企微管理后台-管理工具-客户与上下游api-设置接收事件服务器',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'Ext_EncodingAESKey',
        'title' => '客户回调EncodingAESKey',
        'group' => '客户联系',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '企微管理后台-管理工具-客户与上下游api-设置接收事件服务器',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'kf_address_secret',
        'title' => '微信客服Secret',
        'group' => '微信客服',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '企业微信管理后台-微信客服应用-API-Secret获取',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'kf_Token',
        'title' => '微信客服回调Token',
        'group' => '微信客服',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '企业微信管理后台-微信客服应用-API-设置接收事件服务器',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'kf_EncodingAESKey',
        'title' => '微信客服EncodingAESKey',
        'group' => '微信客服',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '企业微信管理后台-微信客服应用-API-设置接收事件服务器',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'agent_Token',
        'title' => '自建应用回调Token',
        'group' => '应用回调',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '企微管理后台-应用管理-功能-接受消息-设置接收事件服务器',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'agent_EncodingAESKey',
        'title' => '自建应用EncodingAESKey',
        'group' => '应用回调',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '企微管理后台-应用管理-功能-接受消息-设置接收事件服务器',
        'ok' => '',
        'extend' => '',
    ],
];
