<?php
/**
 * 菜单配置文件
 */

return array (
  0 => 
  array (
  ),
  1 => 
  array (
    0 => 
    array (
      'type' => 'file',
      'name' => 'general',
      'title' => '常规管理',
      'icon' => 'fa fa-cogs',
      'url' => '',
      'condition' => '',
      'remark' => '',
      'ismenu' => 1,
      'menutype' => NULL,
      'extend' => '',
      'py' => 'cggl',
      'pinyin' => 'changguiguanli',
      'weigh' => 137,
      'status' => 'normal',
      'sublist' => 
      array (
        0 => 
        array (
          'type' => 'file',
          'name' => 'dashboard',
          'title' => '控制台',
          'icon' => 'fa fa-dashboard',
          'url' => '',
          'condition' => '',
          'remark' => 'Dashboard tips',
          'ismenu' => 1,
          'menutype' => 'addtabs',
          'extend' => '',
          'py' => 'kzt',
          'pinyin' => 'kongzhitai',
          'weigh' => 143,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'dashboard/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 136,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'dashboard/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 135,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'dashboard/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 133,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'dashboard/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 134,
              'status' => 'normal',
            ),
            4 => 
            array (
              'type' => 'file',
              'name' => 'dashboard/multi',
              'title' => '批量更新',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'plgx',
              'pinyin' => 'pilianggengxin',
              'weigh' => 132,
              'status' => 'normal',
            ),
          ),
        ),
        1 => 
        array (
          'type' => 'file',
          'name' => 'general/config',
          'title' => '系统配置',
          'icon' => 'fa fa-cog',
          'url' => '',
          'condition' => '',
          'remark' => 'Config tips',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'xtpz',
          'pinyin' => 'xitongpeizhi',
          'weigh' => 60,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'general/config/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 52,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'general/config/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 51,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'general/config/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 50,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'general/config/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 49,
              'status' => 'normal',
            ),
            4 => 
            array (
              'type' => 'file',
              'name' => 'general/config/multi',
              'title' => '批量更新',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'plgx',
              'pinyin' => 'pilianggengxin',
              'weigh' => 48,
              'status' => 'normal',
            ),
          ),
        ),
        2 => 
        array (
          'type' => 'file',
          'name' => 'general/attachment',
          'title' => '附件配置',
          'icon' => 'fa fa-file-image-o',
          'url' => '',
          'condition' => '',
          'remark' => 'Attachment tips',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'fjpz',
          'pinyin' => 'fujianpeizhi',
          'weigh' => 53,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'general/attachment/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => 'Attachment tips',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 59,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'general/attachment/select',
              'title' => '选择附件',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'xzfj',
              'pinyin' => 'xuanzefujian',
              'weigh' => 58,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'general/attachment/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 57,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'general/attachment/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 56,
              'status' => 'normal',
            ),
            4 => 
            array (
              'type' => 'file',
              'name' => 'general/attachment/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 55,
              'status' => 'normal',
            ),
            5 => 
            array (
              'type' => 'file',
              'name' => 'general/attachment/multi',
              'title' => '批量更新',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'plgx',
              'pinyin' => 'pilianggengxin',
              'weigh' => 54,
              'status' => 'normal',
            ),
          ),
        ),
        3 => 
        array (
          'type' => 'file',
          'name' => 'general/profile',
          'title' => '个人资料',
          'icon' => 'fa fa-user',
          'url' => '',
          'condition' => '',
          'remark' => '',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'grzl',
          'pinyin' => 'gerenziliao',
          'weigh' => 70,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'general/profile/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 33,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'general/profile/update',
              'title' => '更新个人信息',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'gxgrxx',
              'pinyin' => 'gengxingerenxinxi',
              'weigh' => 32,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'general/profile/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 31,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'general/profile/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 30,
              'status' => 'normal',
            ),
            4 => 
            array (
              'type' => 'file',
              'name' => 'general/profile/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 29,
              'status' => 'normal',
            ),
            5 => 
            array (
              'type' => 'file',
              'name' => 'general/profile/multi',
              'title' => '批量更新',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'plgx',
              'pinyin' => 'pilianggengxin',
              'weigh' => 28,
              'status' => 'normal',
            ),
          ),
        ),
        4 => 
        array (
          'type' => 'file',
          'name' => 'general/addon',
          'title' => '高级配置',
          'icon' => 'fa fa-cube',
          'url' => '',
          'condition' => '',
          'remark' => '',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'gjpz',
          'pinyin' => 'gaojipeizhi',
          'weigh' => 29,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'general/addon/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'general/addon/config',
              'title' => '配置',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'pz',
              'pinyin' => 'peizhi',
              'weigh' => 0,
              'status' => 'normal',
            ),
          ),
        ),
        5 => 
        array (
          'type' => 'file',
          'name' => 'general/moneylog',
          'title' => '余额日志',
          'icon' => 'fa fa-money',
          'url' => '',
          'condition' => '',
          'remark' => '',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'yerz',
          'pinyin' => 'yuerizhi',
          'weigh' => 33,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'general/moneylog/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 0,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'general/moneylog/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'general/moneylog/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 0,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'general/moneylog/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            4 => 
            array (
              'type' => 'file',
              'name' => 'general/moneylog/multi',
              'title' => '批量更新',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'plgx',
              'pinyin' => 'pilianggengxin',
              'weigh' => 0,
              'status' => 'normal',
            ),
          ),
        ),
        6 => 
        array (
          'type' => 'file',
          'name' => 'general/scorelog',
          'title' => '积分日志',
          'icon' => 'fa fa-circle-o',
          'url' => '',
          'condition' => '',
          'remark' => '',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'jfrz',
          'pinyin' => 'jifenrizhi',
          'weigh' => 32,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'general/scorelog/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 0,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'general/scorelog/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'general/scorelog/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 0,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'general/scorelog/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            4 => 
            array (
              'type' => 'file',
              'name' => 'general/scorelog/multi',
              'title' => '批量更新',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'plgx',
              'pinyin' => 'pilianggengxin',
              'weigh' => 0,
              'status' => 'normal',
            ),
          ),
        ),
        7 => 
        array (
          'type' => 'file',
          'name' => 'general/withdraw',
          'title' => '提现管理',
          'icon' => 'fa fa-money',
          'url' => '',
          'condition' => '',
          'remark' => '',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'txgl',
          'pinyin' => 'tixianguanli',
          'weigh' => 31,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'general/withdraw/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'general/withdraw/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 0,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'general/withdraw/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 0,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'general/withdraw/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            4 => 
            array (
              'type' => 'file',
              'name' => 'general/withdraw/multi',
              'title' => '批量更新',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'plgx',
              'pinyin' => 'pilianggengxin',
              'weigh' => 0,
              'status' => 'normal',
            ),
          ),
        ),
        8 => 
        array (
          'type' => 'file',
          'name' => 'general/domain',
          'title' => '域名管理',
          'icon' => 'fa fa-circle-o',
          'url' => '',
          'condition' => '',
          'remark' => '',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'ymgl',
          'pinyin' => 'yumingguanli',
          'weigh' => 30,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'general/domain/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 0,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'general/domain/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'general/domain/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 0,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'general/domain/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            4 => 
            array (
              'type' => 'file',
              'name' => 'general/domain/multi',
              'title' => '批量更新',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'plgx',
              'pinyin' => 'pilianggengxin',
              'weigh' => 0,
              'status' => 'normal',
            ),
          ),
        ),
      ),
    ),
  ),
  2 => 
  array (
    0 => 
    array (
      'type' => 'file',
      'name' => 'auth',
      'title' => '权限管理',
      'icon' => 'fa fa-group',
      'url' => '',
      'condition' => '',
      'remark' => '',
      'ismenu' => 1,
      'menutype' => NULL,
      'extend' => '',
      'py' => 'qxgl',
      'pinyin' => 'quanxianguanli',
      'weigh' => 99,
      'status' => 'normal',
      'sublist' => 
      array (
        0 => 
        array (
          'type' => 'file',
          'name' => 'auth/admin',
          'title' => '账号管理',
          'icon' => 'fa fa-user',
          'url' => '',
          'condition' => '',
          'remark' => 'Admin tips',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'zhgl',
          'pinyin' => 'zhanghaoguanli',
          'weigh' => 118,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'auth/admin/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => 'Admin tips',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 117,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'auth/admin/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 116,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'auth/admin/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 115,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'auth/admin/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 114,
              'status' => 'normal',
            ),
          ),
        ),
        1 => 
        array (
          'type' => 'file',
          'name' => 'auth/adminlog',
          'title' => '日志管理',
          'icon' => 'fa fa-list-alt',
          'url' => '',
          'condition' => '',
          'remark' => 'Admin log tips',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'rzgl',
          'pinyin' => 'rizhiguanli',
          'weigh' => 113,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'auth/adminlog/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => 'Admin log tips',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 112,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'auth/adminlog/detail',
              'title' => '详情',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'xq',
              'pinyin' => 'xiangqing',
              'weigh' => 111,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'auth/adminlog/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 110,
              'status' => 'normal',
            ),
          ),
        ),
        2 => 
        array (
          'type' => 'file',
          'name' => 'auth/group',
          'title' => '分组管理',
          'icon' => 'fa fa-group',
          'url' => '',
          'condition' => '',
          'remark' => 'Group tips',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'fzgl',
          'pinyin' => 'fenzuguanli',
          'weigh' => 109,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'auth/group/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => 'Group tips',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 108,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'auth/group/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 107,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'auth/group/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 106,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'auth/group/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 105,
              'status' => 'normal',
            ),
          ),
        ),
        3 => 
        array (
          'type' => 'file',
          'name' => 'auth/player',
          'title' => '企业身份',
          'icon' => 'fa fa-address-book',
          'url' => '',
          'condition' => '',
          'remark' => '',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'qysf',
          'pinyin' => 'qiyeshenfen',
          'weigh' => 0,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'auth/player/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'auth/player/add',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 0,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'auth/player/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 0,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'auth/player/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            4 => 
            array (
              'type' => 'file',
              'name' => 'auth/player/multi',
              'title' => '批量更新',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'plgx',
              'pinyin' => 'pilianggengxin',
              'weigh' => 0,
              'status' => 'normal',
            ),
          ),
        ),
        4 => 
        array (
          'type' => 'file',
          'name' => 'auth/agreement',
          'title' => '协议管理',
          'icon' => 'fa fa-circle-o',
          'url' => '',
          'condition' => '',
          'remark' => '',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'xygl',
          'pinyin' => 'xieyiguanli',
          'weigh' => 0,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'auth/agreement/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'auth/agreement/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 0,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'auth/agreement/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 0,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'auth/agreement/detail',
              'title' => '详情',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'xq',
              'pinyin' => 'xiangqing',
              'weigh' => 0,
              'status' => 'normal',
            ),
            4 => 
            array (
              'type' => 'file',
              'name' => 'auth/agreement/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            5 => 
            array (
              'type' => 'file',
              'name' => 'auth/agreement/multi',
              'title' => '批量更新',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'plgx',
              'pinyin' => 'pilianggengxin',
              'weigh' => 0,
              'status' => 'normal',
            ),
          ),
        ),
      ),
    ),
  ),
  3 => 
  array (
    0 => 
    array (
      'type' => 'file',
      'name' => 'user',
      'title' => '会员管理',
      'icon' => 'fa fa-user-circle',
      'url' => '',
      'condition' => '',
      'remark' => '',
      'ismenu' => 1,
      'menutype' => NULL,
      'extend' => '',
      'py' => 'hygl',
      'pinyin' => 'huiyuanguanli',
      'weigh' => 0,
      'status' => 'normal',
      'sublist' => 
      array (
        0 => 
        array (
          'type' => 'file',
          'name' => 'user/user',
          'title' => '会员管理',
          'icon' => 'fa fa-user',
          'url' => '',
          'condition' => '',
          'remark' => '',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'hygl',
          'pinyin' => 'huiyuanguanli',
          'weigh' => 0,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'user/user/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'user/user/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 0,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'user/user/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 0,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'user/user/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            4 => 
            array (
              'type' => 'file',
              'name' => 'user/user/multi',
              'title' => '批量更新',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'plgx',
              'pinyin' => 'pilianggengxin',
              'weigh' => 0,
              'status' => 'normal',
            ),
          ),
        ),
        1 => 
        array (
          'type' => 'file',
          'name' => 'user/group',
          'title' => '会员分组',
          'icon' => 'fa fa-users',
          'url' => '',
          'condition' => '',
          'remark' => '',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'hyfz',
          'pinyin' => 'huiyuanfenzu',
          'weigh' => 0,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'user/group/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 0,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'user/group/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 0,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'user/group/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'user/group/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            4 => 
            array (
              'type' => 'file',
              'name' => 'user/group/multi',
              'title' => '批量更新',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'plgx',
              'pinyin' => 'pilianggengxin',
              'weigh' => 0,
              'status' => 'normal',
            ),
          ),
        ),
        2 => 
        array (
          'type' => 'file',
          'name' => 'user/moneylog',
          'title' => '余额日志',
          'icon' => 'fa fa-money',
          'url' => '',
          'condition' => '',
          'remark' => '',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'yerz',
          'pinyin' => 'yuerizhi',
          'weigh' => 0,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'user/moneylog/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 0,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'user/moneylog/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'user/moneylog/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 0,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'user/moneylog/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            4 => 
            array (
              'type' => 'file',
              'name' => 'user/moneylog/multi',
              'title' => '批量更新',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'plgx',
              'pinyin' => 'pilianggengxin',
              'weigh' => 0,
              'status' => 'normal',
            ),
          ),
        ),
        3 => 
        array (
          'type' => 'file',
          'name' => 'user/scorelog',
          'title' => '积分日志',
          'icon' => 'fa fa-circle-o',
          'url' => '',
          'condition' => '',
          'remark' => '',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'jfrz',
          'pinyin' => 'jifenrizhi',
          'weigh' => 0,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'user/scorelog/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 0,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'user/scorelog/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'user/scorelog/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 0,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'user/scorelog/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            4 => 
            array (
              'type' => 'file',
              'name' => 'user/scorelog/multi',
              'title' => '批量更新',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'plgx',
              'pinyin' => 'pilianggengxin',
              'weigh' => 0,
              'status' => 'normal',
            ),
          ),
        ),
        4 => 
        array (
          'type' => 'file',
          'name' => 'user/withdraw',
          'title' => '提现管理',
          'icon' => 'fa fa-circle-o',
          'url' => '',
          'condition' => '',
          'remark' => '',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'txgl',
          'pinyin' => 'tixianguanli',
          'weigh' => 0,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'user/withdraw/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'user/withdraw/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 0,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'user/withdraw/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 0,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'user/withdraw/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            4 => 
            array (
              'type' => 'file',
              'name' => 'user/withdraw/multi',
              'title' => '批量更新',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'plgx',
              'pinyin' => 'pilianggengxin',
              'weigh' => 0,
              'status' => 'normal',
            ),
          ),
        ),
      ),
    ),
  ),
  4 => 
  array (
    0 => 
    array (
      'type' => 'file',
      'name' => 'web',
      'title' => '官网管理',
      'icon' => 'fa fa-newspaper-o',
      'url' => '',
      'condition' => '',
      'remark' => '',
      'ismenu' => 1,
      'menutype' => NULL,
      'extend' => '',
      'py' => 'gwgl',
      'pinyin' => 'guanwangguanli',
      'weigh' => 0,
      'status' => 'normal',
      'sublist' => 
      array (
        0 => 
        array (
          'type' => 'file',
          'name' => 'web/category',
          'title' => '分类管理',
          'icon' => 'fa fa-circle-o',
          'url' => '',
          'condition' => '',
          'remark' => '',
          'ismenu' => 0,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'flgl',
          'pinyin' => 'fenleiguanli',
          'weigh' => 103,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'web/category/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'web/category/recyclebin',
              'title' => '回收站',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'hsz',
              'pinyin' => 'huishouzhan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'web/category/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 0,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'web/category/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 0,
              'status' => 'normal',
            ),
            4 => 
            array (
              'type' => 'file',
              'name' => 'web/category/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            5 => 
            array (
              'type' => 'file',
              'name' => 'web/category/destroy',
              'title' => '真实删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zssc',
              'pinyin' => 'zhenshishanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            6 => 
            array (
              'type' => 'file',
              'name' => 'web/category/restore',
              'title' => '还原',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'hy',
              'pinyin' => 'huanyuan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            7 => 
            array (
              'type' => 'file',
              'name' => 'web/category/multi',
              'title' => '批量更新',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'plgx',
              'pinyin' => 'pilianggengxin',
              'weigh' => 0,
              'status' => 'normal',
            ),
          ),
        ),
        1 => 
        array (
          'type' => 'file',
          'name' => 'web/content',
          'title' => '内容管理',
          'icon' => 'fa fa-circle-o',
          'url' => '',
          'condition' => '',
          'remark' => '',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'nrgl',
          'pinyin' => 'neirongguanli',
          'weigh' => 102,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'web/content/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'web/content/recyclebin',
              'title' => '回收站',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'hsz',
              'pinyin' => 'huishouzhan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'web/content/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 0,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'web/content/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 0,
              'status' => 'normal',
            ),
            4 => 
            array (
              'type' => 'file',
              'name' => 'web/content/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            5 => 
            array (
              'type' => 'file',
              'name' => 'web/content/destroy',
              'title' => '真实删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zssc',
              'pinyin' => 'zhenshishanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            6 => 
            array (
              'type' => 'file',
              'name' => 'web/content/restore',
              'title' => '还原',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'hy',
              'pinyin' => 'huanyuan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            7 => 
            array (
              'type' => 'file',
              'name' => 'web/content/multi',
              'title' => '批量更新',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'plgx',
              'pinyin' => 'pilianggengxin',
              'weigh' => 0,
              'status' => 'normal',
            ),
          ),
        ),
        2 => 
        array (
          'type' => 'file',
          'name' => 'web/single',
          'title' => '单页管理',
          'icon' => 'fa fa-circle-o',
          'url' => '',
          'condition' => '',
          'remark' => '',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'dygl',
          'pinyin' => 'danyeguanli',
          'weigh' => 111,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'web/single/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'web/single/recyclebin',
              'title' => '回收站',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'hsz',
              'pinyin' => 'huishouzhan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'web/single/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 0,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'web/single/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 0,
              'status' => 'normal',
            ),
            4 => 
            array (
              'type' => 'file',
              'name' => 'web/single/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            5 => 
            array (
              'type' => 'file',
              'name' => 'web/single/destroy',
              'title' => '真实删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zssc',
              'pinyin' => 'zhenshishanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            6 => 
            array (
              'type' => 'file',
              'name' => 'web/single/restore',
              'title' => '还原',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'hy',
              'pinyin' => 'huanyuan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            7 => 
            array (
              'type' => 'file',
              'name' => 'web/single/multi',
              'title' => '批量更新',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'plgx',
              'pinyin' => 'pilianggengxin',
              'weigh' => 0,
              'status' => 'normal',
            ),
          ),
        ),
        3 => 
        array (
          'type' => 'file',
          'name' => 'web/product',
          'title' => '产品管理',
          'icon' => 'fa fa-circle-o',
          'url' => '',
          'condition' => '',
          'remark' => '',
          'ismenu' => 1,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'cpgl',
          'pinyin' => 'chanpinguanli',
          'weigh' => 100,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'web/product/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'web/product/recyclebin',
              'title' => '回收站',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'hsz',
              'pinyin' => 'huishouzhan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'web/product/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 0,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'web/product/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 0,
              'status' => 'normal',
            ),
            4 => 
            array (
              'type' => 'file',
              'name' => 'web/product/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            5 => 
            array (
              'type' => 'file',
              'name' => 'web/product/destroy',
              'title' => '真实删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zssc',
              'pinyin' => 'zhenshishanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            6 => 
            array (
              'type' => 'file',
              'name' => 'web/product/restore',
              'title' => '还原',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'hy',
              'pinyin' => 'huanyuan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            7 => 
            array (
              'type' => 'file',
              'name' => 'web/product/multi',
              'title' => '批量更新',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'plgx',
              'pinyin' => 'pilianggengxin',
              'weigh' => 0,
              'status' => 'normal',
            ),
          ),
        ),
        4 => 
        array (
          'type' => 'file',
          'name' => 'web/product_category',
          'title' => '商品分类',
          'icon' => 'fa fa-circle-o',
          'url' => '',
          'condition' => '',
          'remark' => '',
          'ismenu' => 0,
          'menutype' => NULL,
          'extend' => '',
          'py' => 'spfl',
          'pinyin' => 'shangpinfenlei',
          'weigh' => 101,
          'status' => 'normal',
          'sublist' => 
          array (
            0 => 
            array (
              'type' => 'file',
              'name' => 'web/product_category/index',
              'title' => '查看',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zk',
              'pinyin' => 'zhakan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            1 => 
            array (
              'type' => 'file',
              'name' => 'web/product_category/recyclebin',
              'title' => '回收站',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'hsz',
              'pinyin' => 'huishouzhan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            2 => 
            array (
              'type' => 'file',
              'name' => 'web/product_category/add',
              'title' => '添加',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'tj',
              'pinyin' => 'tianjia',
              'weigh' => 0,
              'status' => 'normal',
            ),
            3 => 
            array (
              'type' => 'file',
              'name' => 'web/product_category/edit',
              'title' => '编辑',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'bj',
              'pinyin' => 'bianji',
              'weigh' => 0,
              'status' => 'normal',
            ),
            4 => 
            array (
              'type' => 'file',
              'name' => 'web/product_category/del',
              'title' => '删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'sc',
              'pinyin' => 'shanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            5 => 
            array (
              'type' => 'file',
              'name' => 'web/product_category/destroy',
              'title' => '真实删除',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'zssc',
              'pinyin' => 'zhenshishanchu',
              'weigh' => 0,
              'status' => 'normal',
            ),
            6 => 
            array (
              'type' => 'file',
              'name' => 'web/product_category/restore',
              'title' => '还原',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'hy',
              'pinyin' => 'huanyuan',
              'weigh' => 0,
              'status' => 'normal',
            ),
            7 => 
            array (
              'type' => 'file',
              'name' => 'web/product_category/multi',
              'title' => '批量更新',
              'icon' => 'fa fa-circle-o',
              'url' => '',
              'condition' => '',
              'remark' => '',
              'ismenu' => 0,
              'menutype' => NULL,
              'extend' => '',
              'py' => 'plgx',
              'pinyin' => 'pilianggengxin',
              'weigh' => 0,
              'status' => 'normal',
            ),
          ),
        ),
      ),
    ),
  ),
);