<?php
/**
 * 菜单配置文件
 */

return array (
  0 => 
  array (
    'type' => 'file',
    'name' => 'smartcard',
    'title' => '智能名片',
    'icon' => 'fa fa-id-card-o',
    'url' => '',
    'condition' => '',
    'remark' => '',
    'ismenu' => 1,
    'menutype' => 'addtabs',
    'extend' => '',
    'py' => 'znmp',
    'pinyin' => 'zhinengmingpian',
    'weigh' => 999,
    'sublist' => 
    array (
      0 => 
      array (
        'type' => 'file',
        'name' => 'smartcard/visitors',
        'title' => '访客',
        'icon' => 'fa fa-user-plus',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'menutype' => NULL,
        'extend' => '',
        'py' => 'fk',
        'pinyin' => 'fangke',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/visitors/import',
            'title' => '导入',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'dr',
            'pinyin' => 'daoru',
            'weigh' => 0,
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/visitors/index',
            'title' => '查看',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'zk',
            'pinyin' => 'zhakan',
            'weigh' => 0,
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/visitors/add',
            'title' => '添加',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'tj',
            'pinyin' => 'tianjia',
            'weigh' => 0,
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/visitors/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'bj',
            'pinyin' => 'bianji',
            'weigh' => 0,
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/visitors/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'sc',
            'pinyin' => 'shanchu',
            'weigh' => 0,
          ),
          5 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/visitors/multi',
            'title' => '批量更新',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'plgx',
            'pinyin' => 'pilianggengxin',
            'weigh' => 0,
          ),
        ),
      ),
      1 => 
      array (
        'type' => 'file',
        'name' => 'smartcard/favor',
        'title' => '标签点赞',
        'icon' => 'fa fa-heart',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'menutype' => NULL,
        'extend' => '',
        'py' => 'bqdz',
        'pinyin' => 'biaoqiandianzan',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/favor/import',
            'title' => '导入',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'dr',
            'pinyin' => 'daoru',
            'weigh' => 0,
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/favor/index',
            'title' => '查看',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'zk',
            'pinyin' => 'zhakan',
            'weigh' => 0,
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/favor/add',
            'title' => '添加',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'tj',
            'pinyin' => 'tianjia',
            'weigh' => 0,
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/favor/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'bj',
            'pinyin' => 'bianji',
            'weigh' => 0,
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/favor/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'sc',
            'pinyin' => 'shanchu',
            'weigh' => 0,
          ),
          5 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/favor/multi',
            'title' => '批量更新',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'plgx',
            'pinyin' => 'pilianggengxin',
            'weigh' => 0,
          ),
        ),
      ),
      2 => 
      array (
        'type' => 'file',
        'name' => 'smartcard/tags',
        'title' => '用户标签',
        'icon' => 'fa fa-tumblr',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'menutype' => NULL,
        'extend' => '',
        'py' => 'yhbq',
        'pinyin' => 'yonghubiaoqian',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/tags/import',
            'title' => '导入',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'dr',
            'pinyin' => 'daoru',
            'weigh' => 0,
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/tags/index',
            'title' => '查看',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'zk',
            'pinyin' => 'zhakan',
            'weigh' => 0,
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/tags/add',
            'title' => '添加',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'tj',
            'pinyin' => 'tianjia',
            'weigh' => 0,
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/tags/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'bj',
            'pinyin' => 'bianji',
            'weigh' => 0,
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/tags/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'sc',
            'pinyin' => 'shanchu',
            'weigh' => 0,
          ),
          5 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/tags/multi',
            'title' => '批量更新',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'plgx',
            'pinyin' => 'pilianggengxin',
            'weigh' => 0,
          ),
        ),
      ),
      3 => 
      array (
        'type' => 'file',
        'name' => 'smartcard/message',
        'title' => '消息管理',
        'icon' => 'fa fa-volume-up',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'menutype' => NULL,
        'extend' => '',
        'py' => 'xxgl',
        'pinyin' => 'xiaoxiguanli',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/message/import',
            'title' => '导入',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'dr',
            'pinyin' => 'daoru',
            'weigh' => 0,
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/message/index',
            'title' => '查看',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'zk',
            'pinyin' => 'zhakan',
            'weigh' => 0,
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/message/add',
            'title' => '添加',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'tj',
            'pinyin' => 'tianjia',
            'weigh' => 0,
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/message/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'bj',
            'pinyin' => 'bianji',
            'weigh' => 0,
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/message/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'sc',
            'pinyin' => 'shanchu',
            'weigh' => 0,
          ),
          5 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/message/multi',
            'title' => '批量更新',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'plgx',
            'pinyin' => 'pilianggengxin',
            'weigh' => 0,
          ),
        ),
      ),
      4 => 
      array (
        'type' => 'file',
        'name' => 'smartcard/theme',
        'title' => '名片主题',
        'icon' => 'fa fa-th',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'menutype' => NULL,
        'extend' => '',
        'py' => 'mpzt',
        'pinyin' => 'mingpianzhuti',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/theme/import',
            'title' => '导入',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'dr',
            'pinyin' => 'daoru',
            'weigh' => 0,
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/theme/index',
            'title' => '查看',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'zk',
            'pinyin' => 'zhakan',
            'weigh' => 0,
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/theme/add',
            'title' => '添加',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'tj',
            'pinyin' => 'tianjia',
            'weigh' => 0,
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/theme/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'bj',
            'pinyin' => 'bianji',
            'weigh' => 0,
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/theme/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'sc',
            'pinyin' => 'shanchu',
            'weigh' => 0,
          ),
          5 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/theme/multi',
            'title' => '批量更新',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'plgx',
            'pinyin' => 'pilianggengxin',
            'weigh' => 0,
          ),
        ),
      ),
      5 => 
      array (
        'type' => 'file',
        'name' => 'smartcard/c',
        'title' => '企业管理',
        'icon' => 'fa fa-address-card',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'menutype' => NULL,
        'extend' => '',
        'py' => 'qygl',
        'pinyin' => 'qiyeguanli',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/cases',
            'title' => '企业成功案例',
            'icon' => 'fa fa-handshake-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 1,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'qycgal',
            'pinyin' => 'qiyechenggonganli',
            'weigh' => 0,
            'sublist' => 
            array (
              0 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/cases/import',
                'title' => '导入',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'dr',
                'pinyin' => 'daoru',
                'weigh' => 0,
              ),
              1 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/cases/index',
                'title' => '查看',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'zk',
                'pinyin' => 'zhakan',
                'weigh' => 0,
              ),
              2 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/cases/add',
                'title' => '添加',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'tj',
                'pinyin' => 'tianjia',
                'weigh' => 0,
              ),
              3 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/cases/edit',
                'title' => '编辑',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'bj',
                'pinyin' => 'bianji',
                'weigh' => 0,
              ),
              4 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/cases/del',
                'title' => '删除',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'sc',
                'pinyin' => 'shanchu',
                'weigh' => 0,
              ),
              5 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/cases/multi',
                'title' => '批量更新',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'plgx',
                'pinyin' => 'pilianggengxin',
                'weigh' => 0,
              ),
            ),
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/category',
            'title' => '企业产品分类',
            'icon' => 'fa fa-skyatlas',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 1,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'qycpfl',
            'pinyin' => 'qiyechanpinfenlei',
            'weigh' => 0,
            'sublist' => 
            array (
              0 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/category/import',
                'title' => '导入',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'dr',
                'pinyin' => 'daoru',
                'weigh' => 0,
              ),
              1 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/category/index',
                'title' => '查看',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'zk',
                'pinyin' => 'zhakan',
                'weigh' => 0,
              ),
              2 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/category/add',
                'title' => '添加',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'tj',
                'pinyin' => 'tianjia',
                'weigh' => 0,
              ),
              3 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/category/edit',
                'title' => '编辑',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'bj',
                'pinyin' => 'bianji',
                'weigh' => 0,
              ),
              4 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/category/del',
                'title' => '删除',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'sc',
                'pinyin' => 'shanchu',
                'weigh' => 0,
              ),
              5 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/category/multi',
                'title' => '批量更新',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'plgx',
                'pinyin' => 'pilianggengxin',
                'weigh' => 0,
              ),
            ),
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/company',
            'title' => '企业列管理',
            'icon' => 'fa fa-newspaper-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 1,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'qylgl',
            'pinyin' => 'qiyelieguanli',
            'weigh' => 0,
            'sublist' => 
            array (
              0 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/company/import',
                'title' => '导入',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'dr',
                'pinyin' => 'daoru',
                'weigh' => 0,
              ),
              1 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/company/index',
                'title' => '查看',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'zk',
                'pinyin' => 'zhakan',
                'weigh' => 0,
              ),
              2 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/company/add',
                'title' => '添加',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'tj',
                'pinyin' => 'tianjia',
                'weigh' => 0,
              ),
              3 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/company/edit',
                'title' => '编辑',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'bj',
                'pinyin' => 'bianji',
                'weigh' => 0,
              ),
              4 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/company/del',
                'title' => '删除',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'sc',
                'pinyin' => 'shanchu',
                'weigh' => 0,
              ),
              5 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/company/multi',
                'title' => '批量更新',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'plgx',
                'pinyin' => 'pilianggengxin',
                'weigh' => 0,
              ),
            ),
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/design',
            'title' => '企业宣传册',
            'icon' => 'fa fa-file-powerpoint-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 1,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'qyxcc',
            'pinyin' => 'qiyexuanchuance',
            'weigh' => 0,
            'sublist' => 
            array (
              0 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/design/import',
                'title' => '导入',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'dr',
                'pinyin' => 'daoru',
                'weigh' => 0,
              ),
              1 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/design/index',
                'title' => '查看',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'zk',
                'pinyin' => 'zhakan',
                'weigh' => 0,
              ),
              2 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/design/add',
                'title' => '添加',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'tj',
                'pinyin' => 'tianjia',
                'weigh' => 0,
              ),
              3 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/design/edit',
                'title' => '编辑',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'bj',
                'pinyin' => 'bianji',
                'weigh' => 0,
              ),
              4 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/design/del',
                'title' => '删除',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'sc',
                'pinyin' => 'shanchu',
                'weigh' => 0,
              ),
              5 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/design/multi',
                'title' => '批量更新',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'plgx',
                'pinyin' => 'pilianggengxin',
                'weigh' => 0,
              ),
            ),
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/goods',
            'title' => '企业产品',
            'icon' => 'fa fa-gratipay',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 1,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'qycp',
            'pinyin' => 'qiyechanpin',
            'weigh' => 0,
            'sublist' => 
            array (
              0 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/goods/import',
                'title' => '导入',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'dr',
                'pinyin' => 'daoru',
                'weigh' => 0,
              ),
              1 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/goods/index',
                'title' => '查看',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'zk',
                'pinyin' => 'zhakan',
                'weigh' => 0,
              ),
              2 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/goods/add',
                'title' => '添加',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'tj',
                'pinyin' => 'tianjia',
                'weigh' => 0,
              ),
              3 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/goods/edit',
                'title' => '编辑',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'bj',
                'pinyin' => 'bianji',
                'weigh' => 0,
              ),
              4 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/goods/del',
                'title' => '删除',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'sc',
                'pinyin' => 'shanchu',
                'weigh' => 0,
              ),
              5 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/goods/multi',
                'title' => '批量更新',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'plgx',
                'pinyin' => 'pilianggengxin',
                'weigh' => 0,
              ),
            ),
          ),
          5 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/news',
            'title' => '企业动态',
            'icon' => 'fa fa-forumbee',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 1,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'qydt',
            'pinyin' => 'qiyedongtai',
            'weigh' => 0,
            'sublist' => 
            array (
              0 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/news/import',
                'title' => '导入',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'dr',
                'pinyin' => 'daoru',
                'weigh' => 0,
              ),
              1 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/news/index',
                'title' => '查看',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'zk',
                'pinyin' => 'zhakan',
                'weigh' => 0,
              ),
              2 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/news/add',
                'title' => '添加',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'tj',
                'pinyin' => 'tianjia',
                'weigh' => 0,
              ),
              3 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/news/edit',
                'title' => '编辑',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'bj',
                'pinyin' => 'bianji',
                'weigh' => 0,
              ),
              4 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/news/del',
                'title' => '删除',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'sc',
                'pinyin' => 'shanchu',
                'weigh' => 0,
              ),
              5 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/news/multi',
                'title' => '批量更新',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'plgx',
                'pinyin' => 'pilianggengxin',
                'weigh' => 0,
              ),
            ),
          ),
          6 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/staff',
            'title' => '企业员工管理',
            'icon' => 'fa fa-users',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 1,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'qyyggl',
            'pinyin' => 'qiyeyuangongguanli',
            'weigh' => 0,
            'sublist' => 
            array (
              0 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/staff/import',
                'title' => '导入',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'dr',
                'pinyin' => 'daoru',
                'weigh' => 0,
              ),
              1 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/staff/index',
                'title' => '查看',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'zk',
                'pinyin' => 'zhakan',
                'weigh' => 0,
              ),
              2 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/staff/add',
                'title' => '添加',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'tj',
                'pinyin' => 'tianjia',
                'weigh' => 0,
              ),
              3 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/staff/edit',
                'title' => '编辑',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'bj',
                'pinyin' => 'bianji',
                'weigh' => 0,
              ),
              4 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/staff/del',
                'title' => '删除',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'sc',
                'pinyin' => 'shanchu',
                'weigh' => 0,
              ),
              5 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/staff/multi',
                'title' => '批量更新',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'plgx',
                'pinyin' => 'pilianggengxin',
                'weigh' => 0,
              ),
            ),
          ),
          7 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/sc',
            'title' => '企业员工申请',
            'icon' => 'fa fa-user',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'qyygsq',
            'pinyin' => 'qiyeyuangongshenqing',
            'weigh' => 0,
            'sublist' => 
            array (
              0 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/sc/import',
                'title' => '导入',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'dr',
                'pinyin' => 'daoru',
                'weigh' => 0,
              ),
              1 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/sc/index',
                'title' => '查看',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'zk',
                'pinyin' => 'zhakan',
                'weigh' => 0,
              ),
              2 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/sc/add',
                'title' => '添加',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'tj',
                'pinyin' => 'tianjia',
                'weigh' => 0,
              ),
              3 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/sc/edit',
                'title' => '编辑',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'bj',
                'pinyin' => 'bianji',
                'weigh' => 0,
              ),
              4 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/sc/del',
                'title' => '删除',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'sc',
                'pinyin' => 'shanchu',
                'weigh' => 0,
              ),
              5 => 
              array (
                'type' => 'file',
                'name' => 'smartcard/sc/multi',
                'title' => '批量更新',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'plgx',
                'pinyin' => 'pilianggengxin',
                'weigh' => 0,
              ),
            ),
          ),
          8 => 
          array (
            'type' => 'file',
            'name' => 'smartcard/companyadmin',
            'title' => '企业管理员',
            'icon' => 'fa fa-address-book-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'qygly',
            'pinyin' => 'qiyeguanliyuan',
            'weigh' => 0,
          ),
        ),
      ),
    ),
  ),
);